"""Provider-neutral video metadata generation interfaces and fake provider."""

from dataclasses import dataclass, field
from typing import Any, Protocol

from ai_media_os.schemas.video_metadata import ChapterItem, VideoMetadataDocument
from ai_media_os.utils.hashing import hash_json

JsonDict = dict[str, Any]


@dataclass(frozen=True)
class MetadataGenerationRequest:
    project_id: str
    channel_id: str
    channel_name: str
    working_title: str
    topic: str
    script_version_id: str
    script_content: str
    scene_plan_version_id: str
    render_id: str | None
    target_platform: str = "youtube"
    target_language: str = "en"
    tone: str = "clear AI documentary"
    keyword_hints: list[str] = field(default_factory=list)
    title_count: int = 5
    tag_count: int = 12
    prompt_version: str = "metadata-prompt-v1"
    input_hashes: list[str] = field(default_factory=list)
    scenes: list[tuple[float, str]] = field(default_factory=list)


@dataclass(frozen=True)
class MetadataGenerationResult:
    document: VideoMetadataDocument
    provider: str
    model: str
    model_version: str
    prompt_version: str
    metadata: JsonDict = field(default_factory=dict)


class MetadataGenerationProvider(Protocol):
    provider_name: str
    model_name: str
    model_version: str

    def generate(self, request: MetadataGenerationRequest) -> MetadataGenerationResult:
        """Generate a metadata document."""


class FakeMetadataGenerationProvider:
    """Create deterministic metadata without network or LLM dependencies."""

    provider_name = "fake_metadata"
    model_name = "rules-based-metadata"
    model_version = "v1"

    def generate(self, request: MetadataGenerationRequest) -> MetadataGenerationResult:
        fingerprint = hash_json(
            {
                "project_id": request.project_id,
                "script_version_id": request.script_version_id,
                "scene_plan_version_id": request.scene_plan_version_id,
                "render_id": request.render_id,
                "topic": request.topic,
                "tone": request.tone,
                "keyword_hints": request.keyword_hints,
                "input_hashes": request.input_hashes,
            }
        )
        keywords = _keywords(request.topic, request.keyword_hints, request.tag_count)
        title_base = _title_case(request.working_title or request.topic)
        title_ideas = _title_ideas(title_base, keywords, request.title_count)
        title = title_ideas[0]
        chapters = [
            ChapterItem(start_seconds=start, title=_chapter_title(text))
            for start, text in request.scenes
        ]
        if not chapters:
            chapters = [ChapterItem(start_seconds=0, title="Opening")]
        hashtags = [f"#{_hashtag(item)}" for item in keywords[:5]]
        description = (
            f"{title}\n\n"
            f"In this {request.channel_name} episode, we break down {request.topic} with a "
            "clear, source-aware structure for viewers who want the practical implications.\n\n"
            "Chapters:\n"
            + "\n".join(
                f"{_timestamp(chapter.start_seconds)} {chapter.title}" for chapter in chapters
            )
            + "\n\n"
            "This local draft was generated by AI Media OS for human review before publishing."
        )
        document = VideoMetadataDocument(
            platform=request.target_platform,
            title=title,
            title_ideas=title_ideas,
            description=description,
            tags=keywords,
            hashtags=hashtags,
            chapters=chapters,
            language=request.target_language,
            target_audience="AI & Future viewers interested in practical AI shifts",
            keywords=keywords,
            source_script_version_id=request.script_version_id,
            source_scene_plan_version_id=request.scene_plan_version_id,
            source_render_id=request.render_id,
            warnings=["Rules-based draft; review title accuracy and packaging strength."],
            pinned_comment_idea="What AI shift do you think matters most this year?",
        )
        return MetadataGenerationResult(
            document=document,
            provider=self.provider_name,
            model=self.model_name,
            model_version=self.model_version,
            prompt_version=request.prompt_version,
            metadata={"fingerprint": fingerprint, "rules_based": True},
        )


def _keywords(topic: str, hints: list[str], limit: int) -> list[str]:
    words = [
        word.strip(".,:;!?()[]{}").lower()
        for word in f"{topic} {' '.join(hints)}".split()
        if len(word.strip(".,:;!?()[]{}")) > 2
    ]
    defaults = ["ai", "future tech", "artificial intelligence", "automation", "technology"]
    seen: set[str] = set()
    result: list[str] = []
    for word in words + defaults:
        key = word.casefold()
        if key not in seen:
            result.append(word)
            seen.add(key)
        if len(result) >= limit:
            break
    return result


def _title_ideas(title_base: str, keywords: list[str], count: int) -> list[str]:
    ideas = [
        _limit_title(title_base),
        _limit_title(f"{title_base}: What Changes Next"),
        _limit_title(f"The Future of {keywords[0].title()}"),
        _limit_title(f"{keywords[0].title()} Is Moving Fast"),
        _limit_title(f"Why {title_base} Matters Now"),
    ]
    return ideas[: max(1, count)]


def _limit_title(value: str) -> str:
    return value[:97].rstrip() + "..." if len(value) > 100 else value


def _title_case(value: str) -> str:
    return " ".join(part.capitalize() if part.islower() else part for part in value.split())


def _chapter_title(text: str) -> str:
    words = text.replace("\n", " ").split()
    return _limit_title(" ".join(words[:8]) or "Scene")


def _hashtag(value: str) -> str:
    return "".join(character for character in value.title() if character.isalnum()) or "AI"


def _timestamp(seconds: float) -> str:
    total = int(seconds)
    minutes, second = divmod(total, 60)
    hour, minute = divmod(minutes, 60)
    if hour:
        return f"{hour}:{minute:02d}:{second:02d}"
    return f"{minute}:{second:02d}"
